language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update && sudo apt-get install -y pkg-config
  - ./autogen.sh

branches:
  only:
    - master
    - testing

notifications:
  email: true

os:
  - linux