language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update && sudo apt-get install -y pkg-config
  - ./autogen.sh

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux