.\" Copyright (c) 2009 Linux Foundation, written by Michael Kerrisk
.\"     <mtk.manpages@gmail.com>
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.TH LIBPIPECOLORS 7 2015-07-01 "Linux" "libpipecolors"
.SH NAME
libpipecolors \- print old bbs/renegade style pipecodes in c/c++
.SH DESCRIPTION

.I libpipecolors
is a library that parses a string with pipe color codes
.B |01
and replaces them with ansi color codes for the linux terminal.
.SS Other C libraries
.UR http://www.uclibc.org/
.I uClibc
.UE ,
.UR http://www.fefe.de/dietlibc/
.I dietlibc
.UE ,
and
.UR http://www.musl-libc.org/
.I "musl libc"
.UE .
Details of these libraries are covered by the
.I man-pages
project, where they are known.
.SH SEE ALSO
.BR pcprintf (3),
.BR pcsprintf (3),
.SH COLOPHON
This page is part of release 0.1 of
.I libpipecolors
.
A description of the project,
information about reporting bugs,
and the latest version of this page,
can be found at
\%https://github.com/sk-5/libpipecolors/.
