.\" Copyright (c) 2015 Eric Wheeler (eric@rewiv.com)
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.\" 2015-07-06 eric@rewiv.com \- initial program
.\"
.TH libpipecolors 3 2015-07-06 "LIBPIPECOLORS" "libpipecolors c++/c library"
.SH NAME
libpipecolors \- print old bbs/renegade style pipecodes in c/c++
.SH SYNOPSIS
.B #include <pipecolors.h>
.sp
.B using namespace pipecolors;
.SH DESCRIPTION
\fIlibpipecolors\fR is a library that parses a string with pipe color codes \fB|01\fR and replaces them with ansi color codes for the linux terminal.
.SS On the web
.PR
https://github.com/sk-5/libpipecolors/

.SH SEE ALSO
.BR pcprintf (3),
.BR pcsprintf (3)
